repos:
  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.9.0
    hooks:
      - id: black
        args: [--line-length, '90']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.13.3
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Don't use ruff format since we use black
      # Run the formatter.
      # - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.8.23
    hooks:
      # Update the uv lockfile
      - id: uv-lock